#!/bin/bash

echo "🐚 Shell Artifact Demo"
echo "======================"
echo ""
echo "Hello from HandBox Artifact System!"
echo ""
echo "System Information:"
echo "  OS: $(uname -s)"
echo "  Architecture: $(uname -m)"
echo "  Current date: $(date)"
echo "  Current user: $(whoami)"
echo "  Working directory: $(pwd)"
echo ""
echo "✅ Shell artifact executed successfully!"
